In [144]:
# import required libraries
import pandas as pd
import json

In [109]:
with open('hotel_reviews.json','r') as json_file:
    json_data = json.load(json_file)
json_file.close()

In [141]:
# set up function that returns JSON data to a Pandas dataframe
def cooler_hotel_reviews(data):
    """
    data = expects a json type object like json_data from above
    """
    df = pd.DataFrame(data['Reviews'])
    df_ratings = df.Ratings.dropna().apply(pd.Series) # Ratings is a dictionary witin the json_data, so unpacking here to Columns
    df = (pd
          .concat([df,df_ratings], axis = 1)
          .drop(columns=['Ratings']))
    df.Date = pd.to_datetime(df.Date)
    df.set_index('ReviewID', inplace = True)
    
    return df

In [143]:
help(cooler_hotel_reviews)

Help on function cooler_hotel_reviews in module __main__:

cooler_hotel_reviews(data)
    data = expects a json type object like json_data from above

In [142]:
df = cooler_hotel_reviews(json_data).copy()
df.head()

,Author,AuthorLocation,Content,Date,Title,Service,Cleanliness,Overall,Value,Sleep Quality,Rooms,Location,"Business service (e.g., internet access)",Check in / front desk
ReviewID,,,,,,,,,,,,,,
UR126946257,gowharr32,Boston,We enjoyed the Best Western Pioneer Square. My...,2012-03-29,“Excellent Hotel & Location”,4,5,5.0,4,4,5,5,NaN,NaN
UR126795011,Nancy W,"Madison, Wisconsin",Great visit to Seattle thanks to our stay at t...,2012-03-27,“Great Visit to Seattle!”,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN
UR126715331,Janet H,"Ketchikan, Alaska","Great Location,short walk from Amtrak station,...",2012-03-27,“Excellent in Everyway”,5,5,5.0,5,5,5,5,NaN,NaN
UR126585393,TimothyFlorida,Florida,Accommodation in Seattle can be expensive. Thi...,2012-03-24,"“Great hotel, location & price.”",5,5,5.0,5,4,4,5,NaN,NaN
UR126067021,KarenArmstrong_BC,"Armstrong, BC",Very cool old building in a great location. Ch...,2012-03-13,“Cool place”,3,4,4.0,3,3,3,5,NaN,NaN